### PR TITLE
add sys path and mkdir ranking_results folder before using it

### PR DESCRIPTION
**Pull request by happygirlzt**
1. Appended the current working folder to sys path, otherwise, it cannot find the library to import.
2. If we do not make the directory (i.e., ranking_results) before referring to it, the program will raise an error.
3. I also changed the quote format to source code format in readme.md for better use.

### CODE REVIEW

**Comment by happygirlzt** [comment]
Format all the source code parts with the 'source code' style, previously, using the 'quote' style.

**Comment by irving-muller** [comment]
Thank you for the improvements. I was wondering if it would be better to create a empty folder _ranking_results_ and commit it instead of creating this directory in the script _sabd.py_. What do you think?

**Comment by happygirlzt** [comment]
Sure, it's fine too :D

**Comment by happygirlzt** [comment]
> Thank you for the improvements. I was wondering if it would be better to create a empty folder _ranking_results_ and commit it instead of creating this directory in the script _sabd.py_. What do you think?

I commit with a pre-created ranking_results folder. I'll close this pull-request then

**Comment by happygirlzt** [comment]
Ah, I'm not sure what does it mean by 'closing pull-request'. But you can merge it :D

**Comment by irving-muller** [comment]
Me neither. First time that I manage a public repository on github. :)

I merged the pull-request. Thank you for the improvements.

**Pull request merged**
